name: push-to-s3

on:
  workflow_dispatch:

jobs:
  push-to-s3:
    name: "Push Hugo Site To S3"
    runs-on: ubuntu-latest
    steps:
      - name: "Push Hugo Site To S3"
        shell: bash
        run: echo "Hello World"
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GIT_SECRET }}
          repository: zachajon-cisco/b
          event-type: workflow_dispatch
